name: Coveralls

on:
  push:
    branches: [ "main" ]

jobs:
  coverage:
    name: Coverage report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate coverage report
        run: ./vendor/bin/phpunit --coverage-clover coverage.xml
        env:
          XDEBUG_MODE: coverage

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: coverage.xml
          format: clover
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
